language: php
php:
  - 7.0
  - 5.6
  - 5.5
  - 5.4
  - 5.3

before_script:
  - pushd /tmp
  - git clone https://github.com/TysonAndre/runkit7.git
  - pushd runkit7
  - phpize
  - ./configure
  - make
  - make install
  - echo "extension = runkit.so" >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini
  - popd
  - popd
  - composer install
